# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_REDIRECT_URI: 'http://localhost:12345'


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.17
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: wesleyemery
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: US/Central
          plugin_achievements: no
          # plugin_achievements_display: detailed
          plugin_achievements_secrets: no
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_stargazers: no
# 🎼 Music activity and suggestions

#           plugin_music: true

#           plugin_music_provider: "spotify"

#           plugin_music_token: "$SPOTIFY_CLIENT_ID, $SPOTIFY_CLIENT_SECRET, $SPOTIFY_REDIRECT_URI"

#           plugin_music_user: "we3kb.we@gmail.com"

#           plugin_music_mode:
#             description: Display mode
#             default: <default-value>

#           plugin_music_playlist:
#             description: Playlist URL
#             default: <default-value>

#           plugin_music_limit:
#             description: Display limit
#             default: <default-value>

#           plugin_music_played_at:
#             description: Recently played - Last played timestamp
#             default: <default-value>

#           plugin_music_time_range:
#             description: Top tracks - Time range
#             default: <default-value>

#           plugin_music_top_type:
#             description: Top tracks - Display type
#             default: <default-value>

