# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
env:
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_REDIRECT_URI: 'http://localhost:12345'


jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.17
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: wesleyemery
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_followup: yes
          plugin_followup_sections: user, repositories
          plugin_followup_archived: yes
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_skipped: ${{ env.USER_NAME }}
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 1000
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
# 🎼 Music activity and suggestions

#           plugin_music: true

#           plugin_music_provider: "spotify"

#           plugin_music_token: "$SPOTIFY_CLIENT_ID, $SPOTIFY_CLIENT_SECRET, $SPOTIFY_REDIRECT_URI"

#           plugin_music_user: "we3kb.we@gmail.com"

#           plugin_music_mode:
#             description: Display mode
#             default: <default-value>

#           plugin_music_playlist:
#             description: Playlist URL
#             default: <default-value>

#           plugin_music_limit:
#             description: Display limit
#             default: <default-value>

#           plugin_music_played_at:
#             description: Recently played - Last played timestamp
#             default: <default-value>

#           plugin_music_time_range:
#             description: Top tracks - Time range
#             default: <default-value>

#           plugin_music_top_type:
#             description: Top tracks - Display type
#             default: <default-value>

